services:
  db:
    image: mariadb:10.6
    container_name: mariadb-wordpress-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIA_DB_ROOT_PW:-rootpassword}" 
      MYSQL_DATABASE: "${MARIA_DB_NAME:-wordpressDB}" 
      MYSQL_USER: "${MARIA_DB_USER:-dbadmin}"
      MYSQL_PASSWORD: "${MARIA_DB_PASSWORD:-dbadminpass}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    ports:
      - "${WORDPRESS_HTTP_PORT:-8080}:80"     
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST_ADDRESS:-db}:${MC_HOST_PORT:-3306}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-dbadmin}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-dbadminpass}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpressDB}"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
    networks:
      - wpnet

volumes:
  db_data:
  wp_data:
networks:
  wpnet:
